name: Build ZMK firmware (nix)
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v4
    with:
      # Optionally choose the toolchain to use: Zephyr SDK (default) or GNU Arm
      # Embedded ('gnuarmemb'). The latter results in slightly faster builds.
      toolchain: zephyr
      # toolchain: gnuarmemb
      